### ISSUE TITLE
Content edits for http://lanetech.org/quickstart/quickstart-forms.php?page=contact

### ISSUE THREAD

**Issue by heymrhayes** [heymrhayes/quickStart1819#12]
https://docs.google.com/document/d/1Mz1FHtM9ZbdoVjPI03ynSARjqT9b3RH8nq9q6H77qmU/edit

**Comment by elgholston** [comment]
I did not manage this portion of QUick Start. This is where Christine collected the prrofs of address and birth certificates

**Comment by heymrhayes** [comment]
This is the page where they input all the contact information, not the file upload page.

http://lanetech.org/quickstart/quickstart-forms.php?page=contact

**Comment by heymrhayes** [comment]
Ready for review

http://lanetech.org/quickstart/quickstart-forms.php?page=contact
