### ISSUE TITLE
Content edits for http://lanetech.org/quickstart/quickstart-forms.php?page=contract

### ISSUE THREAD

**Issue by heymrhayes** [heymrhayes/quickStart1819#15]
https://docs.google.com/document/d/1amSCIZYU_zzPrJcz5irooeVvtKm786qYg-kA84eOvtM/edit

**Comment by elgholston** [comment]
I added the updates, but the fonts and spacing  did not transfer nicely :(.

**Comment by heymrhayes** [comment]
updated.
