### ISSUE TITLE
Content edits for http://lanetech.org/quickstart/quickstart-forms.php?page=fol

### ISSUE THREAD

**Issue by heymrhayes** [heymrhayes/quickStart1819#19]
https://docs.google.com/document/d/10RF_tuFz_NM-5sap_Y0aYQz5qf79DNYTgem4skyQ6Qo/edit

**Comment by elgholston** [comment]
No changes other than the need for the link. 
Also, they were hoping for their information to appear sooner. I am worried about people not completing the QUick Start process. Any suggestions? SHould this be a separate email blast and then include it at the end of the paclet for those who did not sign up in advance?

**Comment by heymrhayes** [comment]
no changes made for now;  the donation line appears on the Fee page.
