### ISSUE TITLE
Content edits for http://lanetech.org/quickstart/quickstart-forms.php?page=fiif-intro

### ISSUE THREAD

**Issue by heymrhayes** [heymrhayes/quickStart1819#21]
https://docs.google.com/document/d/1fOg6CBv1cuqppuJggIEL_IBCTDz_g-xQ4jPybr8eFiY/edit

**Comment by elgholston** [comment]
I believe Mollie and Jill talked to you about what they need for this form. Please let me know if you need anything else from me.
