### ISSUE TITLE
Content edits for http://lanetech.org/quickstart/quickstart-forms.php?page=fiif

### ISSUE THREAD

**Issue by heymrhayes** [heymrhayes/quickStart1819#22]
https://docs.google.com/document/d/1k0yHj7isOM500GCJ8zr6h3EY0VheclUuxeA_899EiPM/edit

**Comment by elgholston** [comment]
I believe Mollie and Jill talked to you about what they need for this form. Please let me know if there is anything else you need.

**Comment by heymrhayes** [comment]
Updated the form validation on the page to require an income frequency for each income amount.
