### ISSUE TITLE
Content edits for http://lanetech.org/quickstart/quickstart-forms.php?page=compliance

### ISSUE THREAD

**Issue by heymrhayes** [heymrhayes/quickStart1819#26]
https://docs.google.com/document/d/1UDvXKL9TGzmV-mGENJl1rm6W9RX_sCtcRg2PesFtDqY/edit

**Comment by elgholston** [comment]
Completed

**Comment by heymrhayes** [comment]
Received data from S Hanley;  imported into table student_medical; 

page still shows 16-17 CPS page, but no more current page is currently available
