### ISSUE TITLE
Content edits for http://lanetech.org/quickstart/quickstart-forms.php?complete=yes

### ISSUE THREAD

**Issue by heymrhayes** [heymrhayes/quickStart1819#29]
https://docs.google.com/document/d/1FUrKT6S8nwe2sdehtGPfaU9AJHW6vsPELeDq5uGHetw/edit

**Comment by elgholston** [comment]
I contacted the president of the Friends of Lane to have her to send me an updated blurb about the gala.

**Comment by elgholston** [comment]
I contacted the Friends of Lane President to have her send me an updated version of her information.
