### ISSUE TITLE
update sharing for QS Google Docs

### ISSUE THREAD

**Issue by heymrhayes** [heymrhayes/quickStart1819#31]
I was testing some of the Google Doc links, and if I'm not logged in, I'm prompted to do so.

I think this relates to the CPS sharing policy change which eliminated sharing items outside of the @cps domain.

They're recently rescinded _that_ policy, and you can now share outside the domain again, but you'll have to reset the permissions on the documents.

Here's one example:

https://docs.google.com/document/d/1wJPrR7uOwa5Sa4HvnmB5j03GBxHBwpaTBPFWKavro0w/

**Comment by elgholston** [comment]
The FAQ was the only one I had to change. The others were open to other users. Let me know if that works
